#!/bin/bash

# StyleWeave MySQL Quick Setup Script
# This script automates the initial MySQL database setup

echo "🎨 StyleWeave MySQL Quick Setup"
echo "================================"
echo ""

# Check if MySQL is installed
if ! command -v mysql &> /dev/null; then
    echo "❌ MySQL is not installed!"
    echo "Please install MySQL first:"
    echo "  Ubuntu/Debian: sudo apt install mysql-server"
    echo "  macOS: brew install mysql"
    echo "  Windows: Download from https://dev.mysql.com/downloads/"
    exit 1
fi

echo "✅ MySQL is installed"
echo ""

# Prompt for MySQL root password
read -sp "Enter MySQL root password: " ROOT_PASSWORD
echo ""

# Database configuration
DB_NAME="styleweave_db"
DB_USER="styleweave_user"
read -sp "Enter password for styleweave_user: " DB_PASSWORD
echo ""
echo ""

# Create database and user
echo "📊 Creating database and user..."

mysql -u root -p"$ROOT_PASSWORD" << EOF
-- Create database
CREATE DATABASE IF NOT EXISTS $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Create user
CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';

-- Grant permissions
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';

-- Apply changes
FLUSH PRIVILEGES;

-- Verify
SELECT 'Database created successfully!' AS message;
EOF

if [ $? -eq 0 ]; then
    echo "✅ Database and user created successfully!"
else
    echo "❌ Failed to create database. Check your MySQL root password."
    exit 1
fi

# Create config.py
echo ""
echo "📝 Creating configuration file..."

cat > ../backend/config.py << EOF
# StyleWeave MySQL Configuration
# Auto-generated by setup script

DB_CONFIG = {
    'host': 'localhost',
    'user': '$DB_USER',
    'password': '$DB_PASSWORD',
    'database': '$DB_NAME',
    'port': 3306,
    'charset': 'utf8mb4',
    'autocommit': False
}

# Flask Configuration
SECRET_KEY = 'dev-secret-key-change-in-production'
DEBUG = True
UPLOAD_FOLDER = 'static/uploads'
MAX_CONTENT_LENGTH = 16 * 1024 * 1024  # 16MB max file size
EOF

echo "✅ Configuration file created: backend/config.py"

# Initialize database schema and seed data
echo ""
echo "🌱 Initializing database schema..."

cd ../backend
python3 << EOF
from services.database import init_db

db = init_db()
db.init_database()
db.seed_database()
print("\n✅ Database initialized with sample data!")
EOF

if [ $? -eq 0 ]; then
    echo ""
    echo "🎉 Setup Complete!"
    echo ""
    echo "Next steps:"
    echo "  1. Test connection: python3 db_manager.py stats"
    echo "  2. View fabrics: python3 db_manager.py fabrics"
    echo "  3. View templates: python3 db_manager.py templates"
    echo ""
    echo "Database credentials:"
    echo "  Database: $DB_NAME"
    echo "  Username: $DB_USER"
    echo "  Password: [hidden]"
else
    echo "❌ Failed to initialize database"
    exit 1
fi